import {test} from 'node:test';import assert from 'node:assert/strict';
import {products,preview,quote,normalizeItems,validateCustomer} from '../server/catalog.js';
import {handleRequest,getCatalog} from '../server/store.js';
const SKU=products[0].variants[0].sku;
const item={sku:SKU,quantity:2};
const customer={fullName:'Test Customer',email:'test@example.com',phone:'0900000000',country:'VN',province:'Test city',ward:'Test ward',address:'Sample street 1',note:''};
const req=(action,data,headers={})=>new Request('https://pikli-website.vercel.app/api/store?action='+action,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://pikli-website.vercel.app',...headers},body:JSON.stringify(data)});
test('all placeholder products remain unapproved',()=>assert.ok(products.every(p=>p.approved===false)));
test('catalogue has distinct valid SKUs',()=>{const skus=products.flatMap(p=>p.variants.map(v=>v.sku));assert.equal(new Set(skus).size,skus.length);});
test('server ignores manipulated client prices',()=>assert.equal(quote([{...item,price:1,lineTotal:1}],preview).subtotal,998000));
test('unset shipping is null, NOT falsely free',()=>{const q=quote([item],preview);assert.equal(q.shipping,null);assert.equal(q.total,null);assert.equal(q.orderEnabled,false);});
test('duplicate variants aggregate before quantity limits',()=>assert.deepEqual(normalizeItems([{sku:SKU,quantity:1},{sku:SKU,quantity:2}]),[{sku:SKU,quantity:3}]));
test('rejects 11 of a variant after duplicate aggregation',()=>assert.throws(()=>normalizeItems([{sku:SKU,quantity:6},{sku:SKU,quantity:5}])));
test('rejects negative/fractional/string/NaN quantities',()=>{for(const quantity of [-1,0,1.5,'2',NaN])assert.throws(()=>normalizeItems([{sku:SKU,quantity}]));});
test('rejects unknown SKU',()=>assert.throws(()=>quote([{sku:'fake_sku_123',quantity:1}],preview)));
test('live stock and approval must both pass',()=>{const c=structuredClone(preview);c.mode='live';assert.throws(()=>quote([item],c));c.products[0].approved=true;c.products[0].variants[0].available=1;assert.throws(()=>quote([item],c));});
test('configured shipping and thresholds are calculated server-side',()=>{const c=structuredClone(preview);c.shipping.fee=30000;c.shipping.freeOver=900000;assert.equal(quote([item],c).total,998000);assert.equal(quote([{...item,quantity:1}],c).total,529000);});
test('validates customer and country',()=>{assert.equal(validateCustomer(customer).country,'VN');for(const bad of [{...customer,email:'bad'},{...customer,phone:'abc'},{...customer,country:'US'},{...customer,address:''}])assert.throws(()=>validateCustomer(bad));});
test('preview catalog runs without DB or secrets',async()=>{const r=await handleRequest(new Request('https://pikli-website.vercel.app/api/store'),{});const c=await r.json();assert.equal(r.status,200);assert.equal(c.orderEnabled,false);assert.equal(c.connected,false);});
test('real orders are blocked with no configured DB',async()=>{const r=await handleRequest(req('order',{items:[item],customer}),{});assert.equal(r.status,503);assert.equal((await r.json()).error,'STORE_NOT_READY');});
test('cross-origin POST is rejected',async()=>{const r=await handleRequest(req('quote',{items:[item]},{Origin:'https://evil.example'}),{});assert.equal(r.status,403);});
test('non JSON body and oversized requests rejected',async()=>{let r=await handleRequest(req('quote',{items:[item]},{'Content-Type':'text/plain'}),{});assert.equal(r.status,415);r=await handleRequest(req('quote',{data:'x'.repeat(20000)}),{});assert.equal(r.status,413);});
test('waitlist does not falsely claim a registration',async()=>{const r=await handleRequest(req('waitlist',{email:'test@example.com'}),{});assert.equal(r.status,503);});
test('order lookup without token is denied',async()=>{const r=await handleRequest(req('order-status',{orderId:'00000000-0000-0000-0000-000000000000'}),{});assert.equal(r.status,404);});
test('configured upstream failure fails closed; no fallback live order',async()=>{const r=await handleRequest(req('order',{}),{SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'test'},async()=>new Response('bad',{status:500}));assert.equal(r.status,503);});
test('server switch alone does not enable checkout',async()=>{const c=await getCatalog({SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'test',PIKLI_LIVE_APPROVED:'true'},async()=>Response.json({...preview,orderEnabled:true}));assert.equal(c.orderEnabled,false);});
